### ISSUE TITLE
The program has shut down, why? (screenshot)

### ISSUE THREAD

**Issue by stantonhive** [Etayson/Etarkangaroo#3]
![image](https://github.com/Etayson/Etarkangaroo/assets/49280269/fb07bb70-b487-46fd-b0c9-ab64d2d1a728)

**Comment by stantonhive** [comment]
the cards stood without external intervention for 3 days. The only thing that was reduced after the first day was the tension, because the high temperatures outside made themselves felt.

**Comment by stantonhive** [comment]
![image](https://github.com/Etayson/Etarkangaroo/assets/49280269/1a4ce285-0ed7-41ad-abe0-7c28e7d46aeb)

The last file was sent today at 03:00 at night, after 06:00 it shut down, and did not send anything else to the server, tell me is it worth just restarting the program?

**Comment by Etayson** [comment]
First, don't save your work every 5 minutes. The size of your working file is only 0.01-0.02MB. (You are just wasting hard drive)
In your case, save at least 3-6 hours.
And what is GPU on screenshot? Because even 1660s have average speed 860MK/s
The unexpected shutdown of the kangaroo may well be due to some kind of fatal error in the GPU, etc.
And yes you can just restart the client.

**Comment by stantonhive** [comment]
thanks, GPU 3070, I wrote below that the voltage was reduced due to the fact that it was +40 outside, this installation worked like this for 2 days.

**Comment by stantonhive** [comment]
Etar, thanks for the response to the appeal, changed the settings, saving the work every 6 hours. I already thought that there was progress in the solution and the program was closed)
